#load("//tools/test:test.bzl", "TestInfo", "cp_test")

cc_binary(
    name = "0027-deputat-rating",
    srcs = ["0027-deputat-rating.cpp"],
    deps = ["//include:stdlib"],
)

#test1 = TestInfo(
#    input = "in1.txt",
#    output = "ans1.txt",
#)
#
#test2 = TestInfo(
#    input = "in2.txt",
#    output = "ans2.txt",
#)

#cp_test(
#    name = "0027-deputat-rating-test",
#    prog = ":0027-deputat-rating",
#    tests = [
#        # ":test1",
#        # ":test2",
#    ],
#)
