package(default_visibility = ["//visibility:public"])

cc_library(
    name = "stdlib",
    hdrs = ["bits/stdc++.h"],
    strip_include_prefix = "",
)

cc_library(
    name = "debug",
    hdrs = ["debug.h"],
    strip_include_prefix = "",
)
