package(default_visibility = ["//visibility:public"])

cc_library(
    name = "stdlib",
    hdrs = ["bits/stdc++.h"],
    strip_include_prefix = "",
)

cc_library(
    name = "tourist",
    hdrs = glob(["tourist/*.hpp"]),
    strip_include_prefix = "",
)
